#!/usr/bin/env python3
"""Guard the report's wording against accidental change.

Every user-facing string — the layer descriptions, the tab copy, each stage,
each box on every page — is extracted into content/copy-snapshot.json. That
file is the record of what the report currently says.

    python3 check-content.py            report anything that has changed
    python3 check-content.py --accept   approve the current wording as the new
                                        baseline (do this when a change is
                                        intended, and only then)

The point is that a change to wording is never silent. An edit made by mistake
shows up here as a diff; an edit made on purpose is approved explicitly.

Each string is keyed by a hash of *itself*, not by its position. Position-keyed
entries made the guard weak in exactly the case it exists for: inserting one
label renumbered everything after it, so a single addition produced a wall of
false "changed" lines — and a real edit could ride along inside that noise
unread. Keyed by content, an insertion is one ADDED line and nothing else moves.
"""
import json, re, sys, pathlib, html, hashlib, difflib

ROOT = pathlib.Path(__file__).parent
SNAP = ROOT / 'content' / 'copy-snapshot.json'

# the tables that carry prose rather than data, in either file
TABLES = ['LAYERS','CHAIN','HOWTO','TABINTRO','LAYER_MATERIALS','LAYER_RISKS',
          'LAYER_ELEMENTS','MOATWHY','SOURCES','PSOURCES','CONC','PROC','MATS',
          'MATTBL','RISKS','GW','HU','LOOPWHY','DEPLOY','ENVIRO','EL_CODES','BREAKS',
          'CDESC','DESIGN_MODEL','COMETA','LAYER_METRICS','METRIC_FRAME','ATLAS_CARDS','ATLAS_REGIONS_TEXT','ATLAS_WORLD_TEXT',
          'ATLAS_ROUTE_TEXT']
PAGES = ['index.html','stack.html','investor.html','markets.html','environment.html',
         'projects.html','method.html','sources.html','404.html']
MIN_LEN = 4           # short enough to cover tab labels and buttons
# The footer is generated by bump-assets.py and carries the last commit date,
# so it changes on every commit. Holding generated text in a baseline of
# authored wording would make the guard cry wolf on every push.
GENERATED = re.compile(r'^Road to AGI — revision ')

NOISE = re.compile(r'^(?:[\d.,%+\-$£€\s]+|[a-z0-9_-]+\.(?:js|css|png|svg|json|html)'
                   r'|https?://\S+|[A-Za-z]+:[A-Za-z0-9.\-]+|assets/\S+|var\(--\S+\)'
                   r'|[a-z-]+(?: [a-z-]+)*\s*[:;{]\S*'
                   r'|\w+>\w+)$')          # an atlas route key, not prose


def strings_in(src, start):
    """Yield (depth1_key, text) for every string literal inside one object,
       tracking which top-level entry we are under."""
    i = src.index('{', start)
    depth = 0
    key = '_'
    pending = ''
    out = []
    while i < len(src):
        c = src[i]
        if c in '\'"`':
            q = c
            i += 1
            buf = []
            while i < len(src):
                if src[i] == '\\':
                    buf.append(src[i:i+2]); i += 2; continue
                if src[i] == q:
                    break
                buf.append(src[i]); i += 1
            text = ''.join(buf)
            if len(text) >= MIN_LEN and not NOISE.match(text):
                out.append((key, text))
            pending = ''
            i += 1
            continue
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return out
        elif depth == 1:
            m = re.match(r'\s*[,{]?\s*["\']?([A-Za-z0-9_]+)["\']?\s*:', src[i:])
            if m and (src[i-1] in '{,' or src[i-1].isspace()):
                key = m.group(1)
        i += 1
    return out


def key_for(snap, group, text):
    """A content-addressed key, so a string keeps its identity wherever it
       moves. The same text can legitimately appear twice in one group, so
       repeats take a #1, #2 suffix in the order they are found."""
    base = '%s/%s' % (group, hashlib.sha1(text.encode('utf-8')).hexdigest()[:10])
    k, n = base, 0
    while k in snap:
        n += 1
        k = '%s#%d' % (base, n)
    return k


def collect():
    snap = {}
    # Prose lives in both files: the content tables were split into
    # assets/content.js, but a few — BREAKS, DESIGN_MODEL, EL_CODES — sit
    # beside the code that uses them. Scanning only one silently drops them.
    for path in (ROOT / 'assets' / 'content.js', ROOT / 'script.js'):
        src = path.read_text()
        for t in TABLES:
            m = re.search(r'\bconst ' + t + r'\s*=\s*[\{\[]', src)
            if not m:
                continue
            for key, text in strings_in(src, m.start()):
                snap[key_for(snap, '%s/%s/%s' % (path.name, t, key), text)] = text

    # The no-script summary is generated from LAYERS by build-content.py, so its
    # words are already in the baseline at source. Counting them again would
    # double every edit and make a one-line change look like two.
    tag = re.compile(r'<(script|style|noscript)\b.*?</\1>', re.S | re.I)
    for page in PAGES:
        p = ROOT / page
        if not p.exists():
            continue
        body = tag.sub(' ', p.read_text())
        body = re.sub(r'<!--.*?-->', ' ', body, flags=re.S)
        for chunk in re.split(r'<[^>]+>', body):
            text = html.unescape(re.sub(r'\s+', ' ', chunk)).strip()
            if len(text) >= MIN_LEN and not NOISE.match(text) and not GENERATED.match(text):
                snap[key_for(snap, page, text)] = text
    return snap


def pair_edits(was, now, added, removed):
    """An edit shows up as one removal and one addition. Match them back up
       inside a group so the report reads as a before-and-after rather than as
       two unrelated events; anything left over really was added or removed."""
    group = lambda k: k.rsplit('/', 1)[0]
    pool = {}
    for k in removed:
        pool.setdefault(group(k), []).append(k)
    edits, still_added = [], []
    for k in added:
        cands = pool.get(group(k), [])
        best, score = None, 0.0
        for c in cands:
            s = difflib.SequenceMatcher(None, was[c], now[k]).ratio()
            if s > score:
                best, score = c, s
        if best is not None and score >= 0.6:
            cands.remove(best)
            edits.append((best, k))
        else:
            still_added.append(k)
    matched = {a for a, _ in edits}
    return edits, still_added, [k for k in removed if k not in matched]


def main():
    now = collect()
    if '--accept' in sys.argv:
        SNAP.parent.mkdir(exist_ok=True)
        SNAP.write_text(json.dumps(now, indent=1, ensure_ascii=False, sort_keys=True) + '\n')
        print('baseline accepted: %d strings recorded' % len(now))
        return 0
    if not SNAP.exists():
        print('no baseline yet. Run: python3 check-content.py --accept')
        return 1
    was = json.loads(SNAP.read_text())
    added = [k for k in now if k not in was]
    removed = [k for k in was if k not in now]
    if not (added or removed):
        print('wording unchanged: %d strings match the baseline' % len(now))
        return 0
    edits, added, removed = pair_edits(was, now, added, removed)
    def show(title, keys, get):
        if not keys:
            return
        print('\n%s (%d)' % (title, len(keys)))
        for k in keys[:40]:
            label = k[1] if isinstance(k, tuple) else k
            print('  %s\n      %s' % (label, get(k)[:150]))
        if len(keys) > 40:
            print('  … and %d more' % (len(keys) - 40))
    show('CHANGED', edits,
         lambda e: '- ' + was[e[0]][:150] + '\n      + ' + now[e[1]][:150])
    show('REMOVED', removed, lambda k: was[k])
    show('ADDED', added, lambda k: now[k])
    print('\nIf these changes are intended: python3 check-content.py --accept')
    return 1


if __name__ == '__main__':
    sys.exit(main())
